version: "3"

services:

  web: 
    volumes:
    - ./:/var/www/html
    build: .
    ports: [ "8000:80" ]


  db:
    image: mysql:latest
    container_name: portfolio10-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: portfolio
    ports:
      - 3306:3306
  